version: "3"

services:
  front:
    container_name: tech-tools-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/opt/frontend
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
